### ISSUE TITLE
ClassNotFound

### ISSUE THREAD

**Issue by Maxetto** [Xephi/AuthMeReloaded#88]
Testing out latest build with a fresh Spigot 1.8.7 server and AuthMe only, i got this error on Login and Register commands:

[03:12:51] [Server thread/WARN]: [AuthMe] Task #16 for AuthMe v5.0-SNAPSHOT generated an exception
java.lang.NoClassDefFoundError: com/maxmind/geoip/LookupService
	at fr.xephi.authme.AuthMe.getCountryName(AuthMe.java:709) ~[?:?]
	at fr.xephi.authme.AuthMe.replaceAllInfos(AuthMe.java:767) ~[?:?]
	at fr.xephi.authme.process.register.ProcessSyncronousPasswordRegister.run(ProcessSyncronousPasswordRegister.java:145) ~[?:?]
	at org.bukkit.craftbukkit.v1_8_R3.scheduler.CraftTask.run(CraftTask.java:71) ~[spigot187.jar:git-Spigot-f928e7a-e91aed8]
	at org.bukkit.craftbukkit.v1_8_R3.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:350) [spigot187.jar:git-Spigot-f928e7a-e91aed8]
	at net.minecraft.server.v1_8_R3.MinecraftServer.B(MinecraftServer.java:726) [spigot187.jar:git-Spigot-f928e7a-e91aed8]
	at net.minecraft.server.v1_8_R3.DedicatedServer.B(DedicatedServer.java:367) [spigot187.jar:git-Spigot-f928e7a-e91aed8]
	at net.minecraft.server.v1_8_R3.MinecraftServer.A(MinecraftServer.java:657) [spigot187.jar:git-Spigot-f928e7a-e91aed8]
	at net.minecraft.server.v1_8_R3.MinecraftServer.run(MinecraftServer.java:560) [spigot187.jar:git-Spigot-f928e7a-e91aed8]
	at java.lang.Thread.run(Unknown Source) [?:1.8.0_45]
Caused by: java.lang.ClassNotFoundException: com.maxmind.geoip.LookupService
	at java.net.URLClassLoader.findClass(Unknown Source) ~[?:1.8.0_45]
	at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:101) ~[spigot187.jar:git-Spigot-f928e7a-e91aed8]
	at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:86) ~[spigot187.jar:git-Spigot-f928e7a-e91aed8]
	at java.lang.ClassLoader.loadClass(Unknown Source) ~[?:1.8.0_45]
	at java.lang.ClassLoader.loadClass(Unknown Source) ~[?:1.8.0_45]
	... 10 more

And this, after a restart where i activated email recovery (plugin won't start in this case):

[03:30:57] [Server thread/ERROR]: Error occurred while enabling AuthMe v5.0-SNAPSHOT (Is it up to date?)
java.lang.NoClassDefFoundError: javax/mail/Message
	at fr.xephi.authme.AuthMe.onEnable(AuthMe.java:173) ~[?:?]
	at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:321) ~[spigot187.jar:git-Spigot-f928e7a-e91aed8]
	at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:340) [spigot187.jar:git-Spigot-f928e7a-e91aed8]
	at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:405) [spigot187.jar:git-Spigot-f928e7a-e91aed8]
	at org.bukkit.craftbukkit.v1_8_R3.CraftServer.loadPlugin(CraftServer.java:356) [spigot187.jar:git-Spigot-f928e7a-e91aed8]
	at org.bukkit.craftbukkit.v1_8_R3.CraftServer.enablePlugins(CraftServer.java:316) [spigot187.jar:git-Spigot-f928e7a-e91aed8]
	at net.minecraft.server.v1_8_R3.MinecraftServer.s(MinecraftServer.java:418) [spigot187.jar:git-Spigot-f928e7a-e91aed8]
	at net.minecraft.server.v1_8_R3.MinecraftServer.k(MinecraftServer.java:382) [spigot187.jar:git-Spigot-f928e7a-e91aed8]
	at net.minecraft.server.v1_8_R3.MinecraftServer.a(MinecraftServer.java:337) [spigot187.jar:git-Spigot-f928e7a-e91aed8]
	at net.minecraft.server.v1_8_R3.DedicatedServer.init(DedicatedServer.java:256) [spigot187.jar:git-Spigot-f928e7a-e91aed8]
	at net.minecraft.server.v1_8_R3.MinecraftServer.run(MinecraftServer.java:528) [spigot187.jar:git-Spigot-f928e7a-e91aed8]
	at java.lang.Thread.run(Unknown Source) [?:1.8.0_45]
Caused by: java.lang.ClassNotFoundException: javax.mail.Message
	at java.net.URLClassLoader.findClass(Unknown Source) ~[?:1.8.0_45]
	at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:101) ~[spigot187.jar:git-Spigot-f928e7a-e91aed8]
	at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:86) ~[spigot187.jar:git-Spigot-f928e7a-e91aed8]
	at java.lang.ClassLoader.loadClass(Unknown Source) ~[?:1.8.0_45]
	at java.lang.ClassLoader.loadClass(Unknown Source) ~[?:1.8.0_45]
	... 12 more

**Comment by Xephi** [comment]
Did you compile it yourself ?

**Comment by Maxetto** [comment]
Jenkins build

**Comment by sgdc3** [comment]
@Xephi launch a new build manually

**Comment by Xephi** [comment]
Done, idk why API's are not shaded :')

**Comment by sgdc3** [comment]
let me see if there are problems with pom file

**Comment by sgdc3** [comment]
Wait, yesterday I made an huge change in the pom file: changed group id from fr.xephi.authme.AuthMe to fr.xephi.authme

**Comment by sgdc3** [comment]
But I don't think this is the cause of the problem now...

**Comment by Xephi** [comment]
didn't affect it :/ just tested it now

**Comment by sgdc3** [comment]
:/ try to reset jenkins working directory and purge his m2 local repo

**Comment by sgdc3** [comment]
Xephi, there are too much old issues without response from the author, we should close them for the moment ...

**Comment by sgdc3** [comment]
@Maxetto Ho visto che hai lavorato su un antibot, se ne hai voglia potresti cercare di migliorare quello nativo di authme? ;)

**Comment by sgdc3** [comment]
Thanks @Xephi ;)

**Comment by Maxetto** [comment]
Eh, è dura migliorare quello nativo di AuthMe, per svariati motivi. Si potrebbero unire i progetti, però c'è gente che magari vuole usare xAuth o nessun tipo di plugin di login (Online mode) e comunque avere protezione dai Bot proxati.

**Comment by Xephi** [comment]
I've reset .m2 and remove workspace, still the problem, i think i need to add some shade things like that : 

```xml
			<plugin>
				<groupId>org.apache.maven.plugins</groupId>
				<artifactId>maven-shade-plugin</artifactId>
				<version>2.3</version>
				<configuration>
					<artifactSet>
						<includes>
							<include>com.maxmind.geoip:*</include>
							<include>javax.mail:*</include>
							<include>com.sun.mail:*</include>
							<include>com.comphenix.attribute:*</include>
						</includes>
					</artifactSet>
				</configuration>
				<executions>
					<execution>
						<phase>package</phase>
						<goals>
							<goal>shade</goal>
						</goals>
					</execution>
				</executions>
			</plugin>
```

**Comment by sgdc3** [comment]
yeah, but why there are only now the problems?

**Comment by Xephi** [comment]
I don't know, it appears since i change the distribution on vps :')

**Comment by sgdc3** [comment]
have you updated maven on the machine?

**Comment by sgdc3** [comment]
Probably it's because of a different maven executable...

**Comment by sgdc3** [comment]
Just add the shade plugin ;)

**Comment by Xephi** [comment]
i think i use maven 3.3.3 :')

**Comment by Xephi** [comment]
Fixed !

**Comment by Jecvay** [comment]
[10:35:46 INFO]: Jecvay[/119.131.76.144:55522] logged in with entity id 4090 at ([world]-8855.553935098622, 81.0, -19503.69999998808)
[10:35:46 INFO]:  Jecvay 拖着缓慢的步伐, 走进了服务器.
[10:35:46 INFO]: [AuthMe] Jecvay logged in!
[10:35:46 WARN]: [AuthMe] Task #5655 for AuthMe v5.2-SNAPSHOT-b1476 generated an exception
java.lang.ArrayIndexOutOfBoundsException
        at java.lang.System.arraycopy(Native Method) ~[?:1.8.0_111]
        at fr.xephi.authme.libs.maxmind.geoip.LookupService.readNode(LookupService.java:941) ~[?:?]
        at fr.xephi.authme.libs.maxmind.geoip.LookupService.seekCountry(LookupService.java:918) ~[?:?]
        at fr.xephi.authme.libs.maxmind.geoip.LookupService.getCountry(LookupService.java:496) ~[?:?]
        at fr.xephi.authme.libs.maxmind.geoip.LookupService.getCountry(LookupService.java:463) ~[?:?]
        at fr.xephi.authme.libs.maxmind.geoip.LookupService.getCountry(LookupService.java:452) ~[?:?]
        at fr.xephi.authme.service.GeoIpService.getCountryName(GeoIpService.java:131) ~[?:?]
        at fr.xephi.authme.AuthMe.replaceAllInfo(AuthMe.java:362) ~[?:?]
        at fr.xephi.authme.process.login.ProcessSyncPlayerLogin.processPlayerLogin(ProcessSyncPlayerLogin.java:119) ~[?:?]
        at fr.xephi.authme.process.SyncProcessManager.lambda$processSyncPlayerLogin$3(SyncProcessManager.java:51) ~[?:?]
        at org.bukkit.craftbukkit.v1_10_R1.scheduler.CraftTask.run(CraftTask.java:58) ~[patched_1.10.2.jar:git-Paper-916.1]
        at org.bukkit.craftbukkit.v1_10_R1.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:355) [patched_1.10.2.jar:git-Paper-916.1]
        at net.minecraft.server.v1_10_R1.MinecraftServer.D(MinecraftServer.java:798) [patched_1.10.2.jar:git-Paper-916.1]
        at net.minecraft.server.v1_10_R1.DedicatedServer.D(DedicatedServer.java:404) [patched_1.10.2.jar:git-Paper-916.1]
        at net.minecraft.server.v1_10_R1.MinecraftServer.C(MinecraftServer.java:740) [patched_1.10.2.jar:git-Paper-916.1]
        at net.minecraft.server.v1_10_R1.MinecraftServer.run(MinecraftServer.java:639) [patched_1.10.2.jar:git-Paper-916.1]
        at java.lang.Thread.run(Thread.java:745) [?:1.8.0_111]
[10:35:56 INFO]: Jecvay issued server command: /cs qxmt
[10:35:56 INFO]: Jecvay issued mycmd command ID(1) /cs qxmt
[10:35:56 INFO]: Jecvay issued server command: /res tp qxmt

**Comment by Jecvay** [comment]
PaperSpigot 1.10.2

MySQL

**Comment by ljacqu** [comment]
@Jecvay create a new issue, https://github.com/Xephi/AuthMeReloaded/issues/new
